### ISSUE TITLE
Add readme

### ISSUE THREAD

**Issue by lukechronc** [lukechronc/spotify_saved_tracks_update#2]

**Comment by pbeart** [comment]
Just created a fork with a README.MD, just so I can check what this actually does: it seems like it allows you to view all the songs you have 'saved', which is now known as 'Saving to Liked Songs' in newer versions of Spotify, however there is already a 'Liked Songs' page under YOUR LIBRARY so I am a little confused as to what this does.

**Comment by lukechronc** [comment]
Check out my comment in #3, hopefully it explains a little bit

**Comment by pbeart** [comment]
Sorry, somehow I didn't see that

**Comment by pbeart** [comment]
I've updated the readme in my fork

**Comment by lukechronc** [comment]
@tomasnik created the README in #3
